Icone: Fix template and create-desktop-icon function

diff --git a/scripts.d/support/install-setup-common b/scripts.d/support/install-setup-common
--- a/scripts.d/support/install-setup-common
+++ b/scripts.d/support/install-setup-common
@@ -85,37 +85,66 @@ function template-conversion()
 function create-desktop-icon()
 {
     local PREFIX=$1
+    local SALOMEVERSION=$2
     local APPLIDIR_PATH=$HOME/.local/share/applications
-    local DESKTOP_FILE_NAME=Salome_template.desktop
-    local DESKTOP_FILE_VERSION=Salome_V__SALOMEVERSION__.desktop
+    local DESKTOP_FILE_NAME=salome_template.desktop
+    local DESKTOP_FILE_VERSION=salome_V__SALOMEVERSION__.desktop
     local DESKTOPDIR=$(xdg-user-dir DESKTOP)
-
+    local ICONE_FILE=$PREFIX/icon.png
     mv $PREFIX/$DESKTOP_FILE_NAME $PREFIX/$DESKTOP_FILE_VERSION
-    ICONE_FILE=$PREFIX/icon.png
-
-    # de YAMM projects/salome/installer/strings_template.py&
-
     # Install the menu and desktop files if requested
-    if test -e $PREFIX/$DESKTOP_FILE_VERSION; then
+    if [[ -e $PREFIX/$DESKTOP_FILE_VERSION ]]; then
       sed -i "s#APPLIDIR#$PREFIX#g" $PREFIX/$DESKTOP_FILE_VERSION
-      sed -i "s#VERSION#__SALOMEVERSION__#g" $PREFIX/$DESKTOP_FILE_VERSION
-    fi
-
-    if [[ -e $PREFIX/$DESKTOP_FILE_VERSION ]] ; then
-      if [[ ! -d $APPLIDIR_PATH ]] ; then
+      sed -i "s#VERSION#SALOMEVERSION#g" $PREFIX/$DESKTOP_FILE_VERSION
+      if [[ ! -d $APPLIDIR_PATH ]]; then
         mkdir -p $APPLIDIR_PATH  || die "mkdir failed"
       fi
       cp $PREFIX/$DESKTOP_FILE_VERSION $APPLIDIR_PATH/
       chmod +x $APPLIDIR_PATH/$DESKTOP_FILE_VERSION
-    fi
-
-    if test -n $DESKTOPDIR; then
-      if test -e $PREFIX/$DESKTOP_FILE_VERSION; then
-        cp $PREFIX/$DESKTOP_FILE_VERSION $DESKTOPDIR
-        chmod +x $DESKTOPDIR/$DESKTOP_FILE_VERSION
+      if [[ -n $DESKTOPDIR ]]; then
+          cp $PREFIX/$DESKTOP_FILE_VERSION $DESKTOPDIR
+          chmod +x $DESKTOPDIR/$DESKTOP_FILE_VERSION
       fi
     fi
 }
+
+##{
+#    local PREFIX=$1
+#    local SALOMEVERSION=$2
+#    local APPLIDIR_PATH=$HOME/.local/share/applications
+#    local DESKTOP_FILE_NAME=Salome_template.desktop
+#    local DESKTOP_FILE_VERSION=Salome_V__SALOMEVERSION__.desktop
+#    local DESKTOPDIR=$(xdg-user-dir DESKTOP)
+#
+#    mv $PREFIX/$DESKTOP_FILE_NAME $PREFIX/$DESKTOP_FILE_VERSION
+#    ICONE_FILE=$PREFIX/icon.png
+#
+#    # de YAMM projects/salome/installer/strings_template.py&
+#
+#    # Install the menu and desktop files if requested
+#    if test -e $PREFIX/$DESKTOP_FILE_VERSION; then
+#      sed -i "s#APPLIDIR#$PREFIX#g" $PREFIX/$DESKTOP_FILE_VERSION
+#      sed -i "s#VERSION#SALOMEVERSION#g" $PREFIX/$DESKTOP_FILE_VERSION
+#    fi
+#
+#    if [[ -e $PREFIX/$DESKTOP_FILE_VERSION ]] ; then
+#      if [[ ! -d $APPLIDIR_PATH ]] ; then
+#        mkdir -p $APPLIDIR_PATH  || die "mkdir failed"
+#      fi
+#      cp $PREFIX/$DESKTOP_FILE_VERSION $APPLIDIR_PATH/
+#      chmod +x $APPLIDIR_PATH/$DESKTOP_FILE_VERSION
+#    fi
+#
+#    if test -n $DESKTOPDIR; then
+#      if test -e $PREFIX/$DESKTOP_FILE_VERSION; then
+#        cp $PREFIX/$DESKTOP_FILE_VERSION $DESKTOPDIR
+#        chmod +x $DESKTOPDIR/$DESKTOP_FILE_VERSION
+#      fi
+#    fi
+#}
+
+#new
+
 
 # =============================================== get-pck-status
 function get-pck-status()
