Icon: Fix for all

diff --git a/scripts.d/support/install-setup-common b/scripts.d/support/install-setup-common
--- a/scripts.d/support/install-setup-common
+++ b/scripts.d/support/install-setup-common
@@ -86,25 +86,32 @@ function create-desktop-icon()
 {
     local PREFIX=$1
     local SALOMEVERSION=$2
+
     local APPLIDIR_PATH=$HOME/.local/share/applications
     local DESKTOP_FILE_NAME=salome_template.desktop
     local DESKTOP_FILE_VERSION=salome_V$SALOMEVERSION.desktop
     local DESKTOPDIR=$(xdg-user-dir DESKTOP)
     local ICONE_FILE=$PREFIX/icon.png
+
     mv $PREFIX/$DESKTOP_FILE_NAME $PREFIX/$DESKTOP_FILE_VERSION
+
+    [[ $? == 1 ]] && die "cannot create file $PREFIX/$DESKTOP_FILE_VERSION"
+
     # Install the menu and desktop files if requested
-    if [[ -e $PREFIX/$DESKTOP_FILE_VERSION ]]; then
-      sed -i "s#APPLIDIR#$PREFIX#g" $PREFIX/$DESKTOP_FILE_VERSION
-      sed -i "s#VERSION#$SALOMEVERSION#g" $PREFIX/$DESKTOP_FILE_VERSION
-      if [[ ! -d $APPLIDIR_PATH ]]; then
+
+    sed -i "s#APPLIDIR#$PREFIX#g" $PREFIX/$DESKTOP_FILE_VERSION
+    sed -i "s#VERSION#$SALOMEVERSION#g" $PREFIX/$DESKTOP_FILE_VERSION
+
+    if [[ ! -d $APPLIDIR_PATH ]]; then
         mkdir -p $APPLIDIR_PATH  || die "mkdir failed"
-      fi
-      cp $PREFIX/$DESKTOP_FILE_VERSION $APPLIDIR_PATH/
-      chmod +x $APPLIDIR_PATH/$DESKTOP_FILE_VERSION
-      if [[ -n $DESKTOPDIR ]]; then
-          cp $PREFIX/$DESKTOP_FILE_VERSION $DESKTOPDIR
-          chmod +x $DESKTOPDIR/$DESKTOP_FILE_VERSION
-      fi
+    fi
+
+    cp $PREFIX/$DESKTOP_FILE_VERSION $APPLIDIR_PATH/
+    chmod +x $APPLIDIR_PATH/$DESKTOP_FILE_VERSION
+
+    if [[ -n $DESKTOPDIR ]]; then
+        cp $PREFIX/$DESKTOP_FILE_VERSION $DESKTOPDIR
+        chmod +x $DESKTOPDIR/$DESKTOP_FILE_VERSION
     fi
 }
 
